# Generated by Django 3.2.1 on 2021-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vencimento', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('codigoPagamento', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
