# Generated by Django 3.2.1 on 2021-06-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='words_array',
            new_name='words_obj',
        ),
    ]
