# Generated by Django 3.2.1 on 2021-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
