# Generated by Django 3.2.1 on 2021-05-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
