# Generated by Django 3.2.1 on 2021-06-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_rename_words_obj_blacklist_words'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
