# Generated by Django 3.2.1 on 2021-06-04 16:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('words_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
