# Generated by Django 3.2.1 on 2021-06-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_blacklistwords_words_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistwords',
            name='words_array',
            field=models.CharField(max_length=10),
        ),
    ]
